"""
Django settings for leThai project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MAIN_DIR = os.path.dirname(os.path.dirname(__file__))

ON_HEROKU = os.environ.get('ON_HEROKU')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zvb%cxl=pr3l=rrdyj*k6=%ove%8q4@vuyprj_qa@#*4uek%2*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'contact',
    'crispy_forms',
     # The Django sites framework is required
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'profiles',
    'stripe',
    'rest_framework',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'PAGE_SIZE': 10
}

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['main/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.core.context_processors.i18n",
                "django.core.context_processors.media",
                "django.core.context_processors.static",
                "django.core.context_processors.tz",
                "django.core.context_processors.csrf",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

WSGI_APPLICATION = 'main.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

if ON_HEROKU == False :
    # Parse database configuration from $DATABASE_URL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(MAIN_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'daoq758tlishof',
            'USER': 'pwojhgrpgmeevt',
            'PASSWORD': 'ExfsOG97e68BrJTdHU3LeI814r',
            'HOST': 'ec2-107-22-246-250.compute-1.amazonaws.com',
            'PORT': '5432',
        }
    }
    import dj_database_url
    db_from_env = dj_database_url.config(conn_max_age=500)
    DATABASES['default'].update(db_from_env)

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow all host headers
ALLOWED_HOSTS = ['*']

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

# To import static files for css and javascript
STATIC_ROOT = os.path.join(MAIN_DIR, 'staticfiles')

STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(MAIN_DIR, 'main', 'static'),
)

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

# Email
'''
For one who use 2-factor authentication, need to get app password from
https://security.google.com/settings/security/apppasswords?pli=1
also if there's an exception error go to
https://accounts.google.com/DisplayUnlockCaptcha
'''
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'kwarodom@vt.edu'
EMAIL_HOST_PASSWORD = 'fogheflpgpnzjofv'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True

CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Django allauth setting: http://django-allauth.readthedocs.org/en/latest/configuration.html
LOGIN_URL = '/accounts/login/'  # user need to go to this url to login
LOGIN_REDIRECT_URL = '/'  #

ACCOUNT_AUTHENTICATION_METHOD = "username_email"  # username and email
ACCOUNT_CONFIRM_EMAIL_ON_GET = False  # allauth verify if user email has been confirmed
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = LOGIN_URL  # anonymous user will be redirect to this url
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None  # send user to the home page

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # when the link that user signup expire
ACCOUNT_EMAIL_REQUIRED = False  # whether user need to provide email when they signup
ACCOUNT_EMAIL_VERIFICATION = None  #
ACCOUNT_EMAIL_SUBJECT_PREFIX = "My subject: "  # subject of sent email when user signup
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"  # when this site is secure use https

ACCOUNT_LOGOUT_ON_GET = False  # False to ask user whether they really want to logout
ACCOUNT_LOGOUT_REDIRECT_URL = "/"  # url that user will be taken to after logout
ACCOUNT_SIGNUP_FORM_CLASS = None  # to use allauth provided form
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = True  # user has to enter password twice to avoid typo
ACCOUNT_UNIQUE_EMAIL = True  # unique model to signup
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"  #
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"

ACCOUNT_USERNAME_MIN_LENGTH = 5  # min number of character of username
ACCOUNT_USERNAME_BLACKLIST = []  # to blacklist some user
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = False
ACCOUNT_PASSWORD_MIN_LENGTH = 6
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# stripe stiff

# test keys
STRIPE_PUBLISHABLE_KEY = "pk_test_DCgjm5Wotgrm4xARtPiV2CNH"
STRIPE_SECRET_KEY = "sk_test_trkeLOmEAJpTFKN6PqP9PBQg"

# live keys
#STRIPE_PUBLISHABLE_KEY = "pk_live_JXdyRhSm0fx31UzzsKy0x4h1"
#STRIPE_SECRET_KEY = "sk_live_msQ4qOh1TBuGZElZ7eGvwIYU"